// ESRS/CSRD Metrics Definition
// This file contains the 30+ core sustainability metrics that Evidexia can extract

export interface ESRSMetric {
  id: string;
  label: string;
  category: 'Environmental' | 'Social' | 'Governance';
  subcategory: string;
  unit?: string;
  priority: number; // 1-5, where 1 is highest priority
  keywords: string[];
  description: string;
  regulation: string;
}

export const ESRS_METRICS: ESRSMetric[] = [
  // Environmental Metrics (E1-E5)
  {
    id: 'E1-1',
    label: 'Total GHG Emissions (Scope 1)',
    category: 'Environmental',
    subcategory: 'Climate Change',
    unit: 'tCO2e',
    priority: 1,
    keywords: ['scope 1', 'direct emissions', 'ghg emissions', 'greenhouse gas', 'carbon emissions', 'co2 equivalent'],
    description: 'Direct greenhouse gas emissions from owned or controlled sources',
    regulation: 'ESRS E1'
  },
  {
    id: 'E1-2',
    label: 'Total GHG Emissions (Scope 2)',
    category: 'Environmental',
    subcategory: 'Climate Change',
    unit: 'tCO2e',
    priority: 1,
    keywords: ['scope 2', 'indirect emissions', 'electricity', 'purchased energy', 'ghg emissions'],
    description: 'Indirect greenhouse gas emissions from purchased electricity, steam, heating, and cooling',
    regulation: 'ESRS E1'
  },
  {
    id: 'E1-3',
    label: 'Total GHG Emissions (Scope 3)',
    category: 'Environmental',
    subcategory: 'Climate Change',
    unit: 'tCO2e',
    priority: 2,
    keywords: ['scope 3', 'value chain emissions', 'upstream', 'downstream', 'supply chain'],
    description: 'All other indirect greenhouse gas emissions in the value chain',
    regulation: 'ESRS E1'
  },
  {
    id: 'E1-4',
    label: 'Energy Consumption',
    category: 'Environmental',
    subcategory: 'Climate Change',
    unit: 'MWh',
    priority: 1,
    keywords: ['energy consumption', 'electricity usage', 'fuel consumption', 'renewable energy', 'total energy'],
    description: 'Total energy consumption from all sources',
    regulation: 'ESRS E1'
  },
  {
    id: 'E1-5',
    label: 'Renewable Energy Share',
    category: 'Environmental',
    subcategory: 'Climate Change',
    unit: '%',
    priority: 2,
    keywords: ['renewable energy', 'green energy', 'solar', 'wind', 'renewable share', 'clean energy'],
    description: 'Percentage of total energy consumption from renewable sources',
    regulation: 'ESRS E1'
  },
  {
    id: 'E2-1',
    label: 'Air Pollutant Emissions',
    category: 'Environmental',
    subcategory: 'Pollution',
    unit: 'tonnes',
    priority: 3,
    keywords: ['air pollution', 'nox', 'sox', 'particulate matter', 'emissions', 'air quality'],
    description: 'Total emissions of air pollutants including NOx, SOx, and particulate matter',
    regulation: 'ESRS E2'
  },
  {
    id: 'E3-1',
    label: 'Water Consumption',
    category: 'Environmental',
    subcategory: 'Water Resources',
    unit: 'm³',
    priority: 2,
    keywords: ['water consumption', 'water usage', 'water withdrawal', 'fresh water', 'water intake'],
    description: 'Total water consumption across all operations',
    regulation: 'ESRS E3'
  },
  {
    id: 'E3-2',
    label: 'Water Discharge',
    category: 'Environmental',
    subcategory: 'Water Resources',
    unit: 'm³',
    priority: 3,
    keywords: ['water discharge', 'wastewater', 'effluent', 'water treatment', 'discharge volume'],
    description: 'Total volume of water discharged',
    regulation: 'ESRS E3'
  },
  {
    id: 'E4-1',
    label: 'Biodiversity Impact Areas',
    category: 'Environmental',
    subcategory: 'Biodiversity',
    unit: 'hectares',
    priority: 4,
    keywords: ['biodiversity', 'protected areas', 'habitat', 'ecosystem', 'conservation', 'natura 2000'],
    description: 'Total area of operations in or adjacent to biodiversity-sensitive areas',
    regulation: 'ESRS E4'
  },
  {
    id: 'E5-1',
    label: 'Total Waste Generated',
    category: 'Environmental',
    subcategory: 'Circular Economy',
    unit: 'tonnes',
    priority: 2,
    keywords: ['waste generation', 'total waste', 'waste produced', 'waste volume', 'waste tonnage'],
    description: 'Total amount of waste generated by the organization',
    regulation: 'ESRS E5'
  },
  {
    id: 'E5-2',
    label: 'Waste Recycled',
    category: 'Environmental',
    subcategory: 'Circular Economy',
    unit: 'tonnes',
    priority: 3,
    keywords: ['recycled waste', 'waste recycling', 'recycling rate', 'circular economy', 'recovered materials'],
    description: 'Total amount of waste recycled or recovered',
    regulation: 'ESRS E5'
  },
  {
    id: 'E5-3',
    label: 'Hazardous Waste',
    category: 'Environmental',
    subcategory: 'Circular Economy',
    unit: 'tonnes',
    priority: 3,
    keywords: ['hazardous waste', 'toxic waste', 'dangerous waste', 'chemical waste', 'contaminated materials'],
    description: 'Total amount of hazardous waste generated',
    regulation: 'ESRS E5'
  },

  // Social Metrics (S1-S4)
  {
    id: 'S1-1',
    label: 'Total Employee Count',
    category: 'Social',
    subcategory: 'Own Workforce',
    unit: 'FTE',
    priority: 1,
    keywords: ['employee count', 'headcount', 'workforce', 'total employees', 'staff number', 'fte'],
    description: 'Total number of employees (full-time equivalent)',
    regulation: 'ESRS S1'
  },
  {
    id: 'S1-2',
    label: 'Female Employee Percentage',
    category: 'Social',
    subcategory: 'Own Workforce',
    unit: '%',
    priority: 2,
    keywords: ['gender diversity', 'female employees', 'women workforce', 'gender balance', 'female percentage'],
    description: 'Percentage of female employees in total workforce',
    regulation: 'ESRS S1'
  },
  {
    id: 'S1-3',
    label: 'Employee Training Hours',
    category: 'Social',
    subcategory: 'Own Workforce',
    unit: 'hours',
    priority: 3,
    keywords: ['training hours', 'employee development', 'learning', 'professional development', 'training programs'],
    description: 'Total hours of training provided to employees',
    regulation: 'ESRS S1'
  },
  {
    id: 'S1-4',
    label: 'Workplace Injuries',
    category: 'Social',
    subcategory: 'Own Workforce',
    unit: 'incidents',
    priority: 2,
    keywords: ['workplace injuries', 'accidents', 'safety incidents', 'occupational health', 'work-related injuries'],
    description: 'Total number of workplace injuries and accidents',
    regulation: 'ESRS S1'
  },
  {
    id: 'S1-5',
    label: 'Employee Turnover Rate',
    category: 'Social',
    subcategory: 'Own Workforce',
    unit: '%',
    priority: 3,
    keywords: ['employee turnover', 'staff turnover', 'retention rate', 'employee departure', 'attrition'],
    description: 'Annual employee turnover rate',
    regulation: 'ESRS S1'
  },
  {
    id: 'S2-1',
    label: 'Supply Chain Workers',
    category: 'Social',
    subcategory: 'Value Chain Workers',
    unit: 'count',
    priority: 4,
    keywords: ['supply chain workers', 'contractor employees', 'value chain workforce', 'supplier employees'],
    description: 'Number of workers in the value chain',
    regulation: 'ESRS S2'
  },
  {
    id: 'S3-1',
    label: 'Community Investment',
    category: 'Social',
    subcategory: 'Affected Communities',
    unit: '€',
    priority: 4,
    keywords: ['community investment', 'social investment', 'community support', 'local development', 'social programs'],
    description: 'Total investment in community development programs',
    regulation: 'ESRS S3'
  },
  {
    id: 'S4-1',
    label: 'Customer Satisfaction Score',
    category: 'Social',
    subcategory: 'Consumers and End-users',
    unit: 'score',
    priority: 4,
    keywords: ['customer satisfaction', 'client satisfaction', 'customer experience', 'service quality', 'customer rating'],
    description: 'Average customer satisfaction score',
    regulation: 'ESRS S4'
  },

  // Governance Metrics (G1)
  {
    id: 'G1-1',
    label: 'Board Independence',
    category: 'Governance',
    subcategory: 'Business Conduct',
    unit: '%',
    priority: 2,
    keywords: ['board independence', 'independent directors', 'board composition', 'governance structure'],
    description: 'Percentage of independent directors on the board',
    regulation: 'ESRS G1'
  },
  {
    id: 'G1-2',
    label: 'Female Board Members',
    category: 'Governance',
    subcategory: 'Business Conduct',
    unit: '%',
    priority: 3,
    keywords: ['board diversity', 'female directors', 'women on board', 'board gender diversity'],
    description: 'Percentage of female members on the board of directors',
    regulation: 'ESRS G1'
  },
  {
    id: 'G1-3',
    label: 'Ethics Training Coverage',
    category: 'Governance',
    subcategory: 'Business Conduct',
    unit: '%',
    priority: 3,
    keywords: ['ethics training', 'compliance training', 'code of conduct', 'integrity training', 'ethics program'],
    description: 'Percentage of employees who received ethics and compliance training',
    regulation: 'ESRS G1'
  },
  {
    id: 'G1-4',
    label: 'Data Breaches',
    category: 'Governance',
    subcategory: 'Business Conduct',
    unit: 'incidents',
    priority: 2,
    keywords: ['data breaches', 'cyber security incidents', 'data protection', 'privacy violations', 'security breaches'],
    description: 'Number of data breaches and cyber security incidents',
    regulation: 'ESRS G1'
  },
  {
    id: 'G1-5',
    label: 'Anti-corruption Cases',
    category: 'Governance',
    subcategory: 'Business Conduct',
    unit: 'cases',
    priority: 2,
    keywords: ['corruption cases', 'bribery incidents', 'fraud cases', 'compliance violations', 'ethics violations'],
    description: 'Number of confirmed corruption and bribery cases',
    regulation: 'ESRS G1'
  },

  // Additional Financial and Operational Metrics
  {
    id: 'F1-1',
    label: 'Sustainability Investment',
    category: 'Governance',
    subcategory: 'Financial Performance',
    unit: '€',
    priority: 3,
    keywords: ['sustainability investment', 'green investment', 'esg investment', 'environmental investment', 'climate investment'],
    description: 'Total investment in sustainability initiatives',
    regulation: 'Custom'
  },
  {
    id: 'F1-2',
    label: 'Green Revenue',
    category: 'Governance',
    subcategory: 'Financial Performance',
    unit: '€',
    priority: 3,
    keywords: ['green revenue', 'sustainable revenue', 'environmental revenue', 'eco revenue', 'clean revenue'],
    description: 'Revenue from environmentally sustainable activities',
    regulation: 'Custom'
  },
  {
    id: 'O1-1',
    label: 'Sustainability Certifications',
    category: 'Governance',
    subcategory: 'Operational Excellence',
    unit: 'count',
    priority: 4,
    keywords: ['certifications', 'iso 14001', 'iso 45001', 'sustainability standards', 'environmental certifications'],
    description: 'Number of sustainability-related certifications held',
    regulation: 'Custom'
  },
  {
    id: 'O1-2',
    label: 'Supplier ESG Assessment',
    category: 'Social',
    subcategory: 'Value Chain Workers',
    unit: '%',
    priority: 4,
    keywords: ['supplier assessment', 'vendor evaluation', 'supply chain esg', 'supplier sustainability', 'supplier screening'],
    description: 'Percentage of suppliers assessed for ESG criteria',
    regulation: 'Custom'
  }
];

export const getMetricsByCategory = (category: ESRSMetric['category']) => {
  return ESRS_METRICS.filter(metric => metric.category === category);
};

export const getMetricById = (id: string) => {
  return ESRS_METRICS.find(metric => metric.id === id);
};

export const getHighPriorityMetrics = (maxPriority: number = 2) => {
  return ESRS_METRICS.filter(metric => metric.priority <= maxPriority);
};

export const searchMetrics = (query: string) => {
  const lowerQuery = query.toLowerCase();
  return ESRS_METRICS.filter(metric => 
    metric.label.toLowerCase().includes(lowerQuery) ||
    metric.keywords.some(keyword => keyword.toLowerCase().includes(lowerQuery)) ||
    metric.description.toLowerCase().includes(lowerQuery)
  );
};